version: "3.8"

services:
  frontend:
    container_name: split-order-temp
    image: zahidali5/split-frontend-temp
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 19000:19000
      - 19001:19001
